# config/packages/knp_paginator.yaml
knp_paginator:
  page_range: 5                      # Number of links shown around the current page (optional)
  default_options:
    page_name: page                # Query parameter name for page number
    sort_field_name: sort          # Query parameter name for sorting field
    sort_direction_name: direction # Query parameter name for sorting direction
    distinct: true                 # Ensure distinct results, useful with joins
    filter_field_name: filterField # Default query parameter name for filtering field
    filter_value_name: filterValue # Default query parameter name for filtering value
  template:
    pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' # Use Bootstrap 5 template
    sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'             # Default sortable link template
    # filtration: '@KnpPaginator/Pagination/filtration.html.twig'            # Default filtration template