# config/packages/liip_imagine.yaml
liip_imagine:
  # configure resolvers
  resolvers:
    default:
      web_path: ~ # Default web path resolver

  # your filter sets are defined here
  filter_sets:
    cache: ~ # Default cache configuration

    # Existing filter for admin/conducteur lists
    admin_thumb:
      quality: 75
      filters:
        thumbnail:
          size:          [60, 40]
          mode:          outbound # Crop if needed
          allow_upscale: true

    # Existing filter for admin/conducteur show pages
    admin_large_thumb:
      quality: 80
      filters:
        thumbnail:
          size:          [300, 200]
          mode:          inset # Fit within dimensions
          allow_upscale: false

    # Existing filter for public list page (if you added it)
    offer_list_thumb:
      quality: 75
      filters:
        thumbnail:
          size:          [350, 200] # Example size for list card top
          mode:          outbound
          allow_upscale: true

    # --- NEW: Filter for the public offer detail page ---
    public_offer_large:
      quality: 85 # Slightly higher quality for detail view
      filters:
        thumbnail:
          # Adjust size as needed for your detail page layout
          size:          [700, 450]
          # 'inset' mode fits the image within these dimensions without cropping, maintaining aspect ratio.
          # Use 'outbound' if you want it cropped to exactly these dimensions.
          mode:          inset
          allow_upscale: false # Don't make small images blurry by scaling up
    # --- END NEW FILTER SET ---

  # Twig integration mode
  twig:
    mode: lazy