# config/packages/security.yaml

security:
  enable_authenticator_manager: true

  password_hashers:
    App\Entity\User: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    main:
      lazy: true
      provider: app_user_provider
      form_login:
        username_parameter: email
        password_parameter: password
        login_path: app_login
        check_path: app_login
        enable_csrf: true
        csrf_parameter: _csrf_token
        csrf_token_id: authenticate
        success_handler: App\Security\LoginSuccessHandler
      logout:
        path: app_logout
        target: app_login

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/logout, roles: PUBLIC_ACCESS }
